language: php

php:
  - 5.3

before_script:
  - pear channel-discover pear.phpunit.de
  - pear channel-discover components.ez.no
  - pear channel-discover pear.symfony-project.com
  - pear channel-discover pear.symfony.com
  - pear install --alldeps phpunit/PHPUnit
  - pear install --alldeps phpunit/PHPUnit_Selenium

after script:
  - phpunit --verbose DependencyFailureTest.php